### ISSUE TITLE
Inline Newsletter Subscription on homepage

### ISSUE THREAD

**Issue by lancepioch** [pelican-dev/docs#48]

**Comment by QuintenQVD0** [comment]
Something like this but then better I guess?

![afbeelding](https://github.com/pelican-dev/docs/assets/67589015/0b8f41e6-439f-4d83-9d99-f1caffcb52d0)

**Comment by elishasmil3** [comment]
Newsletter is not the part of docusaurus i believe..

**Comment by QuintenQVD0** [comment]
> Newsletter is not the part of docusaurus i believe..

We have a api for that? Its now on a other website?
