### ISSUE TITLE
Color Theme Bug [I THINK]

### ISSUE THREAD

**Issue by NaysKutzu** [pelican-dev/docs#92]
![image](https://github.com/user-attachments/assets/4745376f-d0f1-4cd5-8be6-4363bd5df16a)

![image](https://github.com/user-attachments/assets/ace17eab-1118-4a63-9779-1d5a3a89f29e)

Is this not supposed to be flipped?

**Comment by NaysKutzu** [comment]
Oh cuz it broke my eyes

**Comment by notAreYouScared** [comment]
Those screenshots really need to be updated too... 😄 🤣
